
const ICONTYPES = {
   iconclose: {iconClass: "icon-close_24px", iconTitle: "iconclose"},
    checkCircle: { iconClass: "icon-check_circle" , iconTitle:"checkCircle"},
    iconFill : { iconClass : "icon-Icon-fill", iconTitle: "iconFill"},
    notapplicable : { iconClass : "icon-not-applicable", iconTitle: "notapplicable"},
    iconcheckbox: { iconClass : "icon-checkbox", iconTitle: "iconcheckbox"},
    iconGreentick: { iconClass : "icon-greentick", iconTitle: "iconGreentick"},
    iconUser: { iconClass : "icon-User", iconTitle: "iconUser"},    
    iconactivity: { iconClass : "icon-activity-history", iconTitle: "iconactivity"},
    iconArrow: { iconClass : "icon-Arrow", iconTitle: "iconArrow"},
    iconarrowdrop: { iconClass : "icon-arrow_drop_up_24px", iconTitle: "iconarrowdrop"},
    iconforward: { iconClass : "icon-arrow-forward", iconTitle: "iconforward"},
    iconarrowright: { iconClass : "icon-arrowright", iconTitle: "iconarrowright"},
    iconarrowDirection: { iconClass : "icon--arrow-right", iconTitle: "iconarrowDirection"},
    iconphone: { iconClass : "icon-phone", iconTitle: "iconphone"},
    iconchevron: { iconClass : "icon-chevron-right", iconTitle: "iconchevron"},
    iconclose24: { iconClass : "icon-close24", iconTitle: "iconclose24"},
    iconheand: { iconClass : "icon-heand", iconTitle: "iconheand"},
    iconcurrency: { iconClass : "icon-convert-currency", iconTitle: "iconcurrency"},
    iconedit: { iconClass : "icon-edit", iconTitle: "iconedit"},
    Group: { iconClass : "icon-Group", iconTitle: "Group"},
    iconlocation: { iconClass : "icon-location", iconTitle: "iconlocation"},
    iconalert: { iconClass : "icon-alert", iconTitle: "iconalert"},
    iconMap: { iconClass : "icon-Map", iconTitle: "iconMap"},
    iconnetwork: { iconClass : "icon-network", iconTitle: "iconnetwork"},
    iconnotification: { iconClass : "icon-notification", iconTitle: "iconnotification"},
    iconsettings: { iconClass : "icon-settings", iconTitle: "iconsettings"},
    iconSubtract3: { iconClass : "icon-Subtract3", iconTitle: "iconSubtract3"},
    iconSubtract4: { iconClass : "icon-Subtract4", iconTitle: "iconSubtract4"},
    iconlock: { iconClass : "icon-lock", iconTitle: "iconlock"},
    icontoday: { iconClass : "icon-today", iconTitle: "icontoday"},
    iconUnion: { iconClass : "icon-Union", iconTitle: "iconUnion"},
    webapp: { iconClass : "icon-web-app", iconTitle: "webapp"},
    iconfeedback: { iconClass : "icon-feedback", iconTitle: "iconfeedback"},
    iconVector5: { iconClass : "icon-Vector-5", iconTitle: "iconVector5"},
    iconDollar: { iconClass : "icon-Dollar", iconTitle: "iconDollar"},
    iconrecycle: { iconClass : "icon-recycle", iconTitle: "iconrecycle"},
    iconnotification1: { iconClass : "icon-notification1", iconTitle: "iconnotification1"},
    key: { iconClass : "icon-vpn-key", iconTitle: "key"},
    iconXMLID: { iconClass : "icon-XMLID_161", iconTitle: "iconXMLID"},
    iconHeart: { iconClass : "icon-Heart", iconTitle: "iconHeart"},
    iconReward: { iconClass : "icon-Reward", iconTitle: "iconReward"},
    iconhistory: { iconClass : "icon-activity-history", iconTitle: "iconhistory"},
    iconaverage: { iconClass : "icon-average", iconTitle: "iconaverage"},
    iconGroup1: { iconClass : "icon-Group1", iconTitle: "iconGroup1"},
    dissatisfiedmax: { iconClass : "icon-dissatisfied-max", iconTitle: "dissatisfiedmax"},
    dissatisfiedmedium: { iconClass : "icon-dissatisfied-medium", iconTitle: "dissatisfiedmedium"},
    iconi: { iconClass : "icon-icon-i", iconTitle: "iconi"},
    number2: { iconClass : "icon-number-2 .path1", iconTitle: "number2"},
    number3: { iconClass : "icon-number-2 .path2", iconTitle: "number3"},
    number4: { iconClass : "icon-number-3 .path1", iconTitle: "number4"},
    number5: { iconClass : "icon-number-3 .path2", iconTitle: "number5"},
    number6: { iconClass : "icon-number-4 .path1", iconTitle: "number6"},
    number7: { iconClass : "icon-number-4 .path2", iconTitle: "number7"},
    progress: { iconClass : "icon-progress1", iconTitle: "progress"},
    satisfiedmax: { iconClass : "icon-satisfied-max", iconTitle: "satisfiedmax"},
    satisfiedmedium: { iconClass : "icon-satisfied-medium", iconTitle: "satisfiedmedium"},
    star: { iconClass : "icon-star", iconTitle: "star"},
    equal: { iconClass : "icon-uniE941", iconTitle: "equal"},
    more: { iconClass : "icon-more", iconTitle: "more"},
    iconAdd: { iconClass : "icon-add", iconTitle: "iconAdd"},
    iconArrowDropUp: { iconClass : "icon-arrowDropUp", iconTitle: "iconArrowDropUp"},
    creditCard: { iconClass : "icon-creditCard", iconTitle: "creditCard"},
    chevronDown: { iconClass : "icon-chevron-Down", iconTitle: "chevronDown"},
   


};
const ICONSIZE = {
 LARGE: "icon_large",
 MEDIUM: "icon_medium",
 SMALL: "icon_small",
};
export { ICONTYPES, ICONSIZE };
